version: "3.3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  postgres:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trader
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"