spring:
  application:
    name: traderAPI

  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://db:5432/trader
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    continue-on-error: false
    initialization-mode: always

  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.yaml
    default-schema: trader

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: trader
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false


